apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: kong-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: service1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: kong-hello-world
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: service1 