apiVersion: v1
kind: Namespace
metadata:
  name: kong-system
  labels:
    name: kong-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: kong-hello-world
  labels:
    name: kong-hello-world 