apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: kong-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: service2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: kong-hello-world
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: service2 